#!/bin/bash -e

deploy_file() {
    scp $1 ${HOST_NAME}:/srv/${DEV_NAME}/${PROJ_NAME}/$2
}

mini_banner() {
    echo " "
    echo "x x x x x $1 x x x x x"
    echo " "
}

banner() {
    prefix='------ ' 
    sep='-------------------------------------------------------'
    echo "$sep"
    echo "$prefix $1"
    echo "$sep"
}

HOST_NAME='spa'
DEV_NAME='marilsonc'

# Project name is the last dir of the path.
PROJ_NAME=$(basename `pwd`)
echo $PROJ_DIR

banner "Cleaning target"
sbt clean
echo "."

banner  "Assembling the jar file" 
sbt assembly
echo "."

banner "Uploading jar file"

PKG_PATH=$(ls target/scala-2.11/*.jar)
PKG_FILE=$(echo $PKG_PATH | cut -d'/' -f 3)

echo $PKG_PATH
echo $PKG_FILE

ssh ${HOST_NAME} mkdir -p /srv/${DEV_NAME}/${PROJ_NAME}
deploy_file ${PKG_PATH} ${PKG_FILE}

banner "Uploading scripts ..."
deploy_file run_job run_job
deploy_file remove_target remove_target

mini_banner "Deployment complete"

